#!/usr/bin/env bash

set -euxo pipefail

dependencies=(pre-commit terraform)

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

check_dependency() {
	local dependency=$1
	if ! command -v "$dependency" &>/dev/null; then
		echo "missing"
	fi
}

dependency_error_msg() {
	local dependency=$1
	set +x
	echo -e '\033[0;31m'
	echo "ERROR: Unable to complete setup. Missing dependency: $dependency"
	echo -e '\033[0m'
	set -x
}

for d in "${dependencies[@]}"; do
	ret=$(check_dependency "$d")
	if [ "$ret" = "missing" ]; then
		dependency_error_msg "$d"
		exit 1
	fi
done

# Install pre-commit hooks
pre-commit install

echo "Cleaning up local teraform state"
rm -rf "$script_dir/../.terraform"

backend_config="${TF_BACKEND_CONFIG:-backends/staging.tfvars}"

# Initialize the backend config
terraform init -backend-config "$backend_config"
